### PR TITLE
Fix bug and use the public gateway car response

### LINKED ISSUE #6: Help get unixfs ported to new multiformats
`ipfs-get` directly depends on https://github.com/ipfs/js-ipfs-unixfs/pull/116 but would rather depend on a released version of `ipfs-unix-exporter` for stability.

Help get that PR over the line!

### LINKED ISSUE #12: Switch to  request with Accept: application/vnd.ipld.car
Just so we don't forget,  https://github.com/ipfs/go-ipfs/releases/tag/v0.13.0#support-for-block-and-car-response-formats makes below possible:

```console
$ curl  -H 'Accept: application/vnd.ipld.car' "http://127.0.0.1:8080/ipfs/bafybeiednzu62vskme5wpoj4bjjikeg3xovfpp4t7vxk5ty2jxdi4mv4bu" --output webui.car
$ ipfs dag import webui.car
```

### PR DESCRIPTION
**Pull request by 2color**
This PR introduces several changes:
- fixes a bug arising from the wrong return value in `verifyingBlockService` https://github.com/olizilla/ipfs-get/blob/6a62dfaff76e04961958e7577bdbdfe5d27d00c6/index.js#L49
- Upgrades some of the IPLD/IPFS dependencies 
- Uses the CAR response in gateways based on [the spec](https://github.com/ipfs/specs/blob/main/http-gateways/TRUSTLESS_GATEWAY.md#accept-request-header) 

 
Fixes #12
Fixes #6

### CODE REVIEW

**Comment by olizilla** [comment]
@2color we got a test failure on node 14. Would you be up for removing 14 from the test matrix and adding 18 in this PR?

**Comment by olizilla** [comment]
just to nuance the description and defend my honour ;-)

> fixes a bug arising from the wrong return value

i think the return value here was correct for the old versions of the deps, but needed updating as a result of the upgrade to deal with breaking changes in those apis.

**Comment by 2color** [comment]
>i think the return value here was correct for the old versions of the deps, but needed updating as a result of the upgrade to deal with breaking changes in those apis.

Make sense.

Do you know which dep exactly. My guess is [ipfs-unixfs-exporter](https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs-exporter#recursivecid-blockstore), 

I got help from Alex to figure this out, but my guess is that the following interfaces could have guided me here:

https://github.com/ipfs/js-ipfs-interfaces/blob/73e4cfcf41178fe6e27f0c7b431fb9511e1dda47/packages/interface-blockstore/src/index.ts#L29

https://github.com/ipfs/js-ipfs-interfaces/blob/73e4cfcf41178fe6e27f0c7b431fb9511e1dda47/packages/interface-store/src/index.ts#L48

**Comment by 2color** [comment]
@olizilla Can I merge?

**Review by olizilla — APPROVED** [review]

**Comment by olizilla** [comment]
Go for it!

**Pull request merged**
